### ISSUE TITLE
job details for preexisting jobs

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#15]
how to get this from the API?

**Comment by josteinaj** [comment]
`GET /ws/jobs/{jobId}` ?

**Comment by marisademeglio** [comment]
@josteinaj I'm looking for the original input and option values. It's useful for re-running a job and also for displaying what values the job was started with. For jobs created during the current GUI instantiation, I can get this info, but for jobs already in the pipeline (from a previous GUI instance or from another source), it doesn't seem to be available (as far as I've looked).

**Comment by josteinaj** [comment]
Ok, I see. Those would be useful for the Web UI as well.

**Comment by marisademeglio** [comment]
the GUI will just support jobs created during its current instantiation; closing this for now.
