### ISSUE TITLE
default option values?

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#17]
how to access these from the API?

**Comment by josteinaj** [comment]
Default values is a long-standing issue: daisy/pipeline-issues#188

The workaround in use currently is that the Web UI defaults all boolean options to "true" (strings default to the empty string; and also there's no way to *not* provide an option so the `select` attribute in scripts are always ignored). As a consequence, all options names in our scripts are formulated in a way such that "true" is a good default value, such as "disable X: true/false" and "do not include Y: true/false".

Related issue: daisy/pipeline-framework#84

**Comment by marisademeglio** [comment]
Ok, I've fixed it so the default for boolean values is 'true'. Option strings are empty (they were anyway). The only problem with this is because I can't seem to get job input/option values for pre-existing jobs (see #15), the job details for pre-existing jobs also default to 'true' for boolean options, which might not be accurate.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-framework/pull/90

**Comment by bertfrees** [comment]
@marisademeglio I think we should open this again. The defaults can be accessed from the API now (https://github.com/daisy/pipeline-framework/pull/90), but the GUI doesn't do that yet.

**Comment by bertfrees** [comment]
Currently an empty string is passed which will overwrite the real default values in some scripts (such as the braille scripts). This is even more of a problem when an empty string is passed to an option that has a data-type, for example when an empty string is passes when an integer is expected, this may lead to undesired behavior or even errors.

**Comment by bertfrees** [comment]
Related: https://github.com/daisy/pipeline-gui/issues/58

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/pipeline-gui/pull/61
