### ISSUE TITLE
more menus

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#23]
What other menus do we need at this stage?

**Comment by marisademeglio** [comment]
idea: run job again
this would create a new job form populated with details from the selected job.
users could edit the values or run again as-is

**Comment by josteinaj** [comment]
The ability to re-run a job is very useful, I've seen those using Pipeline 1 doing that all the time, for instance when trying to get a book to validate, making small changes between each run. This will be one of the great advantages of using the GUI over the Web UI. It's just not technically possible to achieve this with the Web UI.

**Comment by marisademeglio** [comment]
idea: copy messages window output to clipboard

**Comment by rdeltour** [comment]
:+1: on this latter, very useful for debugging. Even better: export log file (along with any useful debug info) to a text file or send bug report by email.

**Comment by marisademeglio** [comment]
Added copy messages to clipboard menu item (3e4754dc39d441c40f5b681ad29f2a8541371417)
