### ISSUE TITLE
rename osx application menu

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#26]
Right now, it says "java"... 

https://blog.codecentric.de/en/2015/04/tweaking-the-menu-bar-of-javafx-8-applications-on-os-x/

**Comment by rdeltour** [comment]
Also, the "name" of the app appears to be the Activator's fully qualified class name (as seen in the "Quit" and "Hide" menu items).

**Comment by marisademeglio** [comment]
the easiest way to fix this is to modify fx:application in the ant build script (if we had one). i don't know how this works in our maven environment though. @rdeltour any ideas?
http://stackoverflow.com/questions/23768839/javafx-change-osx-menubar-name

**Comment by marisademeglio** [comment]
This utility should help us but there are dependency issues:
https://github.com/codecentric/NSMenuFX/issues/2

**Comment by rdeltour** [comment]
Done in the OS X package.
