### ISSUE TITLE
menu not working in linux

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#29]
it seems to appear as three dots in the upper left of the window.
![default view after first run](https://cloud.githubusercontent.com/assets/734730/7874915/287966a0-056b-11e5-98aa-658956af05fc.png)

**Comment by marisademeglio** [comment]
user comments: 
* The three-dots-menu-icon does not have a visible descriptive name, such as "More" or "Menu"
* The menu disappears when I release the mouse button, I have to keep the mouse button pressed to show it
* I'm not able to click any of the menu options with the mouse (the keyboard shortcuts works though)

**Comment by marisademeglio** [comment]
@josteinaj would you mind checking to see if this is better now?

**Comment by josteinaj** [comment]
Works perfectly now! :+1:

![skjermbilde fra 2015-06-03 23 27 10](https://cloud.githubusercontent.com/assets/295481/7971864/37b0e300-0a48-11e5-8252-7d0254effaab.png)
