### ISSUE TITLE
grid layout on linux doesn't look right

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#36]
Either it is more conformant than osx or less... 

![dtbook to epub3 - no word wrapping etc](https://cloud.githubusercontent.com/assets/734730/7875019/8cd71af6-056c-11e5-9c73-012d5de16984.png)

**Comment by marisademeglio** [comment]
this should look nicer now. @josteinaj would you mind checking it out?

**Comment by josteinaj** [comment]
Looks much better! :)

![gui looking better](https://cloud.githubusercontent.com/assets/295481/7933148/8a08c5cc-091d-11e5-9361-04ae43636dee.png)
