### ISSUE TITLE
need scrolling on some views

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#37]
for example, the job results list is too long for the window here.

![job details - not enough room for execution log job id setting values etc - not possible to scroll - must resize window](https://cloud.githubusercontent.com/assets/734730/7875036/b5b7805a-056c-11e5-9886-780664928079.png)

**Comment by josteinaj** [comment]
Looking better now :)

![scrolling](https://cloud.githubusercontent.com/assets/295481/7933228/ffbb9bdc-091d-11e5-892c-8cb846548b31.png)
